const songs = [
    { title: "Người tình Mai Ya Hee", genre: "Nhạc xập xình", lyrics: `Ma-ia-hii, Ma-ia-huu...` },
    { title: "Cô đôi thượng ngàn", genre: "Nhạc xập xình", lyrics: `` },
    { title: "Trú Mưa", genre: "Nhạc xập xình", lyrics: `` },
    { title: "Nàng kiều lỡ bước", genre: "Nhạc xập xình", lyrics: `` },
    { title: "Bên anh đêm nay", genre: "Nhạc xập xình", lyrics: `` },
    { title: "Có duyên không nợ", genre: "Nhạc xập xình", lyrics: `` },
    { title: "Phai dấu cuộc tình", genre: "Nhạc xập xình", lyrics: `` },
    { title: "Như một người dưng", genre: "Nhạc xập xình", lyrics: `` },
    { title: "Vở kịch của em", genre: "Nhạc xập xình", lyrics: `` },
    { title: "Hẹn hò nhưng không yêu", genre: "Nhạc xập xình", lyrics: `` },
    { title: "Cánh hoa héo tàn", genre: "Nhạc xập xình", lyrics: `` },
    { title: "Để anh lương thiện", genre: "Nhạc xập xình", lyrics: `` },
    { title: "Nơi vực nơi trời", genre: "Nhạc xập xình", lyrics: `` },
    { title: "Amore Mio", genre: "Nhạc xập xình", lyrics: `` },
    { title: "Tuyết yêu thương", genre: "Nhạc xập xình", lyrics: `` },
    { title: "Thu cuối", genre: "Nhạc xập xình", lyrics: `` },
    { title: "Anh đau từ lúc em đi", genre: "Nhạc xập xình", lyrics: `` },
    { title: "Trói em lại / Thuỷ triều", genre: "Nhạc xập xình", lyrics: `` },
    { title: "Chiếc khăn piêu", genre: "Nhạc xập xình", lyrics: `` },
    { title: "Điều anh biết", genre: "Nhạc xập xình", lyrics: `` },
    { title: "Con bướm xuân", genre: "Nhạc xập xình", lyrics: `` },
    { title: "Không cảm xúc", genre: "Nhạc xập xình", lyrics: `` },
    { title: "ĐỘ TỘC", genre: "Nhạc var", lyrics: `Chào anh em nhá!` },
    { title: "STREAM ĐẾN BAO GIỜ", genre: "Nhạc var", lyrics: `` },
    { title: "Pickleball", genre: "Nhạc var", lyrics: `` },
    { title: "Con trai cưng", genre: "Nhạc var", lyrics: `` },
    { title: "Vị của anh", genre: "Nhạc var", lyrics: `` },
    { title: "Trình", genre: "Nhạc var", lyrics: `` },
    { title: "Không thấy ngày về", genre: "Nhạc var", lyrics: `` },
    { title: "Kiếp đỏ đen", genre: "Nhạc var", lyrics: `` },
    { title: "Tình ca thanh hoá", genre: "Nhạc var", lyrics: `` },
    { title: "Rap thanh hoá", genre: "Nhạc var", lyrics: `` },
    { title: "Last night", genre: "Nhạc var", lyrics: `` },
    { title: "Vì sao tôi là gay", genre: "Nhạc var", lyrics: `` },
    { title: "Như những phút ban đầu", genre: "Nhạc ballad", lyrics: `Nếu như ngày ấy...` },
    { title: "Tha thứ lỗi lầm", genre: "Nhạc ballad", lyrics: `` },
    { title: "Dẫu có lỗi lầm", genre: "Nhạc ballad", lyrics: `` },
    { title: "Cơn mưa tình yêu", genre: "Nhạc ballad", lyrics: `` },
    { title: "Tìm lại bầu trời", genre: "Nhạc ballad", lyrics: `` },
    { title: "Bông hoa đẹp nhất", genre: "Nhạc ballad", lyrics: `` },
    { title: "Suy nghĩ trong anh", genre: "Nhạc ballad", lyrics: `` },
    { title: "Vết mưa", genre: "Nhạc ballad", lyrics: `` },
    { title: "Nơi tình yêu kết thúc", genre: "Nhạc ballad", lyrics: `` },
    { title: "Nơi tình yêu bắt đầu", genre: "Nhạc ballad", lyrics: `` },
    { title: "Một thời đã xa", genre: "Nhạc ballad", lyrics: `` },
    { title: "Gọi tên em trong đêm", genre: "Nhạc ballad", lyrics: `` },
    { title: "Tháng tư là lời nói dối của em", genre: "Nhạc ballad", lyrics: `` },
    { title: "1 phút", genre: "Nhạc ballad", lyrics: `` },
    { title: "Thay tôi yêu cô ấy", genre: "Nhạc ballad", lyrics: `` },
    { title: "Hết thương cạn nhớ", genre: "Nhạc ballad", lyrics: `` },
    { title: "Một bước yêu vạn dặm đau", genre: "Nhạc ballad", lyrics: `` },
    { title: "Anh ơi ở lại", genre: "Nhạc ballad", lyrics: `` },
    { title: "Nếu ngày ấy", genre: "Nhạc ballad", lyrics: `` },
    { title: "Ngày mai người ta đi lấy chồng", genre: "Nhạc ballad", lyrics: `` },
    { title: "Khoá ly biệt", genre: "Nhạc ballad", lyrics: `` },
    { title: "Rồi em sẽ gặp một chàng trai khác", genre: "Nhạc ballad", lyrics: `` },
    { title: "Anh chưa thương em đến vậy đâu", genre: "Nhạc ballad", lyrics: `` },
    { title: "Đừng như thói quen", genre: "Nhạc ballad", lyrics: `` },
    { title: "Chạm đáy nỗi đau", genre: "Nhạc ballad", lyrics: `` },
    { title: "Rời bỏ", genre: "Nhạc ballad", lyrics: `` },
    { title: "Trong trí nhớ của anh", genre: "Nhạc ballad", lyrics: `` },
    { title: "Thương em là điều anh không thể ngờ", genre: "Nhạc ballad", lyrics: `` },
    { title: "Chiều hôm ấy", genre: "Nhạc ballad", lyrics: `` },
    { title: "Giữ em đi", genre: "Nhạc ballad", lyrics: `` },
    { title: "Xe đạp", genre: "Nhạc ballad", lyrics: `` },
    { title: "Chờ ngày anh nhận ra em", genre: "Nhạc ballad", lyrics: `` },
    { title: "Xin đừng lặng im", genre: "Nhạc ballad", lyrics: `` },
    { title: "Đừng ai nhắc về cô ấy", genre: "Nhạc ballad", lyrics: `` },
    { title: "Sao em vô tình", genre: "Nhạc ballad", lyrics: `` },
    { title: "Em không sai chúng ta sai", genre: "Nhạc ballad", lyrics: `` },
    { title: "Phía sau một cô gái", genre: "Nhạc ballad", lyrics: `` },
    { title: "Nếu là anh", genre: "Nhạc ballad", lyrics: "" },
    { title: "Duyên mình lỡ", genre: "Nhạc ballad", lyrics: "" },
    { title: "Chân tình", genre: "Nhạc ballad", lyrics: "" },
    { title: "Thuận theo ý", genre: "Nhạc ballad", lyrics: "" },
    { title: "Em dạo này", genre: "Nhạc ballad", lyrics: "" },
    { title: "Mascara", genre: "Nhạc ballad", lyrics: "" },
    { title: "Cảm ơn và xin lỗi", genre: "Nhạc ballad", lyrics: "" },
    { title: "Vùng ký ức", genre: "Nhạc ballad", lyrics: "" },
    { title: "Ngày chưa giông", genre: "Nhạc ballad", lyrics: "" },
    { title: "Đông kiếm em", genre: "Nhạc ballad", lyrics: "" },
    { title: "Lạ Lùng", genre: "Nhạc ballad", lyrics: "" },
    { title: "Giữ lấy làm gì", genre: "Nhạc ballad", lyrics: "" },
    { title: "Cơn mưa tình yêu", genre: "Song ca", lyrics: "" },
    { title: "Đừng như thói quen", genre: "Song ca", lyrics: "" },
    { title: "Tình yêu màu nắng", genre: "Song ca", lyrics: "" },
    { title: "Mượn rượu tỏ tình", genre: "Song ca", lyrics: "" },
    { title: "Yêu Nắm", genre: "Song ca", lyrics: "" },
    { title: "Thích quá rùi nà", genre: "Song ca", lyrics: "" },
    { title: "Chân ái", genre: "Song ca", lyrics: "" },
    { title: "Người lạ ơi", genre: "Song ca", lyrics: "" },
    { title: "Khó vẽ nụ cười", genre: "Song ca", lyrics: "" },
    { title: "Ex's Hate Me", genre: "Song ca", lyrics: "" },
    { title: "Mặt trời của em", genre: "Song ca", lyrics: "" },
    { title: "Thằng điên", genre: "Song ca", lyrics: "" },
    { title: "Anh đánh rơi người yêu này", genre: "Song ca", lyrics: "" },
    { title: "Cưới nhau đi", genre: "Song ca", lyrics: "" },
    { title: "Bật tình yêu lên", genre: "Song ca", lyrics: "" },
    { title: "Tận cùng nỗi nhớ", genre: "Song ca", lyrics: "" },
    { title: "Từ thích thích thành thương thương", genre: "Song ca", lyrics: "" }
    // --- US-UK BẤT HỦ 🌎 ---
{ title: "Yesterday", genre: "US-UK Bất Hủ", lyrics: `Yesterday, all my troubles seemed so far away\nNow it looks as though they're here to stay\nOh, I believe in yesterday...` },
{ title: "Imagine", genre: "US-UK Bất Hủ", lyrics: `Imagine there's no heaven\nIt's easy if you try\nNo hell below us\nAbove us only sky...` },
{ title: "Bohemian Rhapsody", genre: "US-UK Bất Hủ", lyrics: `Is this the real life?\nIs this just fantasy?\nCaught in a landslide\nNo escape from reality...` },
{ title: "Hotel California", genre: "US-UK Bất Hủ", lyrics: `On a dark desert highway, cool wind in my hair\nWarm smell of colitas, rising up through the air...` },
{ title: "Hey Jude", genre: "US-UK Bất Hủ", lyrics: `Hey Jude, don't make it bad\nTake a sad song and make it better...` },
{ title: "My Heart Will Go On", genre: "US-UK Bất Hủ", lyrics: `Every night in my dreams\nI see you, I feel you\nThat is how I know you go on...` },
{ title: "I Will Always Love You", genre: "US-UK Bất Hủ", lyrics: `If I should stay\nI would only be in your way\nSo I'll go, but I know\nI'll think of you every step of the way...` },
{ title: "Rolling in the Deep", genre: "US-UK Bất Hủ", lyrics: `There's a fire starting in my heart\nReaching a fever pitch and it's bringing me out the dark...` },
{ title: "Shape of You", genre: "US-UK Bất Hủ", lyrics: `The club isn't the best place to find a lover\nSo the bar is where I go...` },
{ title: "Perfect", genre: "US-UK Bất Hủ", lyrics: `I found a love for me\nDarling, just dive right in and follow my lead...` },
{ title: "Thinking Out Loud", genre: "US-UK Bất Hủ", lyrics: `When your legs don't work like they used to before\nAnd I can't sweep you off of your feet...` },
{ title: "All of Me", genre: "US-UK Bất Hủ", lyrics: `Cause all of me loves all of you\nLove your curves and all your edges\nAll your perfect imperfections...` },
{ title: "Hallelujah", genre: "US-UK Bất Hủ", lyrics: `I've heard there was a secret chord\nThat David played, and it pleased the Lord...` },
{ title: "Someone Like You", genre: "US-UK Bất Hủ", lyrics: `I heard that you're settled down\nThat you found a girl and you're married now...` },
{ title: "Hello", genre: "US-UK Bất Hủ", lyrics: `Hello from the other side\nI must have called a thousand times...` },
{ title: "Let Her Go", genre: "US-UK Bất Hủ", lyrics: `Well you only need the light when it's burning low\nOnly miss the sun when it starts to snow...` },
{ title: "Stay With Me", genre: "US-UK Bất Hủ", lyrics: `Won't you stay with me?\n'Cause you're all I need...` },
{ title: "Love Yourself", genre: "US-UK Bất Hủ", lyrics: `My mama don't like you and she likes everyone\nAnd I never like to admit that I was wrong...` },
{ title: "Bad Romance", genre: "US-UK Bất Hủ", lyrics: `I want your ugly, I want your disease\nI want your everything as long as it's free...` },
{ title: "Shallow", genre: "US-UK Bất Hủ", lyrics: `I'm off the deep end, watch as I dive in\nI'll never meet the ground...` },
{ title: "Uptown Funk", genre: "US-UK Bất Hủ", lyrics: `This hit, that ice cold\nMichelle Pfeiffer, that white gold...` },
{ title: "Just the Way You Are", genre: "US-UK Bất Hủ", lyrics: `When I see your face\nThere's not a thing that I would change...` },
{ title: "Sugar", genre: "US-UK Bất Hủ", lyrics: `Sugar, yes please\nWon't you come and put it down on me?` },
{ title: "See You Again", genre: "US-UK Bất Hủ", lyrics: `It's been a long day without you, my friend\nAnd I'll tell you all about it when I see you again...` },
{ title: "Counting Stars", genre: "US-UK Bất Hủ", lyrics: `Lately, I've been, I've been losing sleep\nDreaming about the things that we could be...` },
{ title: "Despacito", genre: "US-UK Bất Hủ", lyrics: `Despacito\nQuiero respirar tu cuello despacito...` },
{ title: "Blinding Lights", genre: "US-UK Bất Hủ", lyrics: `I've been on my own for long enough\nMaybe you can show me how to love, maybe...` },
{ title: "Shake It Off", genre: "US-UK Bất Hủ", lyrics: `Cause the players gonna play, play, play, play, play\nAnd the haters gonna hate, hate, hate, hate, hate...` },
{ title: "Love Story", genre: "US-UK Bất Hủ", lyrics: `Romeo, take me somewhere we can be alone\nI'll be waiting, all there's left to do is run...` },
{ title: "Believer", genre: "US-UK Bất Hủ", lyrics: `First things first\nI'ma say all the words inside my head...` },
{ title: "Viva La Vida", genre: "US-UK Bất Hủ", lyrics: `I used to rule the world\nSeas would rise when I gave the word...` },
{ title: "Yellow", genre: "US-UK Bất Hủ", lyrics: `Look at the stars\nLook how they shine for you...` },
{ title: "Take Me To Church", genre: "US-UK Bất Hủ", lyrics: `Take me to church\nI'll worship like a dog at the shrine of your lies...` },
{ title: "Chandelier", genre: "US-UK Bất Hủ", lyrics: `I'm gonna swing from the chandelier\nFrom the chandelier...` },
{ title: "A Thousand Years", genre: "US-UK Bất Hủ", lyrics: `I have died every day waiting for you\nDarling, don't be afraid I have loved you for a thousand years...` },
{ title: "Let It Go", genre: "US-UK Bất Hủ", lyrics: `Let it go, let it go\nCan't hold it back anymore...` },
{ title: "Stay", genre: "US-UK Bất Hủ", lyrics: `I do the same thing I told you that I never would\nI told you I'd change, even when I knew I never could...` },
{ title: "Heat Waves", genre: "US-UK Bất Hủ", lyrics: `Sometimes, all I think about is you\nLate nights in the middle of June...` },
{ title: "Bad Guy", genre: "US-UK Bất Hủ", lyrics: `So you're a tough guy\nLike it really rough guy...` },
{ title: "Lovely", genre: "US-UK Bất Hủ", lyrics: `Isn't it lovely, all alone\nHeart made of glass, my mind of stone...` },
{ title: "Hero", genre: "US-UK Bất Hủ", lyrics: `And then a hero comes along\nWith the strength to carry on...` },
{ title: "All I Want For Christmas Is You", genre: "US-UK Bất Hủ", lyrics: `I don't want a lot for Christmas\nThere is just one thing I need...` },
{ title: "Girls Like You", genre: "US-UK Bất Hủ", lyrics: `Cause girls like you run 'round with guys like me\n'Til sun comes down when I come through...` },
{ title: "Memories", genre: "US-UK Bất Hủ", lyrics: `Here's to the ones that we got\nCheers to the wish you were here, but you're not...` },
{ title: "Closer", genre: "US-UK Bất Hủ", lyrics: `So baby pull me closer in the backseat of your Rover...` },
{ title: "Wake Me Up", genre: "US-UK Bất Hủ", lyrics: `So wake me up when it's all over\nWhen I'm wiser and I'm older...` },
{ title: "Starboy", genre: "US-UK Bất Hủ", lyrics: `Look what you've done\nI'm a motherf***in' starboy...` },
{ title: "New Rules", genre: "US-UK Bất Hủ", lyrics: `One: Don't pick up the phone\nYou know he's only callin' 'cause he's drunk and alone...` },
{ title: "Havana", genre: "US-UK Bất Hủ", lyrics: `Havana, ooh na-na\nHalf of my heart is in Havana, ooh-na-na...` },
{ title: "Senorita", genre: "US-UK Bất Hủ", lyrics: `I love it when you call me Señorita\nI wish I could pretend I didn't need ya...` },
{ title: "Blank Space", genre: "US-UK Bất Hủ", lyrics: `So it's gonna be forever\nOr it's gonna go down in flames...` },
{ title: "Titanium", genre: "US-UK Bất Hủ", lyrics: `You shout it out, but I can't hear a word you say\nI'm talking loud, not saying much...` },
{ title: "Stitches", genre: "US-UK Bất Hủ", lyrics: `You watch me bleed until I can't breathe\nI'm shaking, falling onto my knees...` },
{ title: "The Scientist", genre: "US-UK Bất Hủ", lyrics: `Come up to meet you, tell you I'm sorry\nYou don't know how lovely you are...` },
{ title: "Fix You", genre: "US-UK Bất Hủ", lyrics: `Lights will guide you home\nAnd ignite your bones\nAnd I will try to fix you...` },
{ title: "Radioactive", genre: "US-UK Bất Hủ", lyrics: `I'm waking up, I feel it in my bones\nEnough to make my systems blow...` },
{ title: "Demons", genre: "US-UK Bất Hủ", lyrics: `When you feel my heat, look into my eyes\nIt's where my demons hide...` },
{ title: "Moves Like Jagger", genre: "US-UK Bất Hủ", lyrics: `I don't need to try to control you\nLook into my eyes and I'll own you...` },
{ title: "Diamonds", genre: "US-UK Bất Hủ", lyrics: `Shine bright like a diamond\nShine bright like a diamond...` },
{ title: "Umbrella", genre: "US-UK Bất Hủ", lyrics: `Under my umbrella, ella, ella, eh, eh, eh...` },
{ title: "Firework", genre: "US-UK Bất Hủ", lyrics: `Baby, you're a firework\nCome on show 'em what you're worth...` },
{ title: "Roar", genre: "US-UK Bất Hủ", lyrics: `I got the eye of the tiger, a fighter\nDancing through the fire...` },
{ title: "One More Night", genre: "US-UK Bất Hủ", lyrics: `But baby there you go again, there you go again, making me love you...` },
{ title: "Payphone", genre: "US-UK Bất Hủ", lyrics: `I'm at a payphone trying to call home\nAll of my change I spent on you...` },
{ title: "Maps", genre: "US-UK Bất Hủ", lyrics: `So I'm following the map that leads to you\nThe map that leads to you...` },
{ title: "Attention", genre: "US-UK Bất Hủ", lyrics: `You just want attention, you don't want my heart\nMaybe you just hate the thought of me with someone new...` },
{ title: "We Don't Talk Anymore", genre: "US-UK Bất Hủ", lyrics: `We don't talk anymore, we don't talk anymore\nWe don't talk anymore like we used to do...` },
{ title: "Don't Start Now", genre: "US-UK Bất Hủ", lyrics: `Don't show up, don't come out\nDon't start caring about me now...` },
{ title: "Drivers License", genre: "US-UK Bất Hủ", lyrics: `I got my driver's license last week\nJust like we always talked about...` },
{ title: "Good 4 U", genre: "US-UK Bất Hủ", lyrics: `Well, good for you, you look happy and healthy\nNot me, if you ever cared to ask...` },
{ title: "Levitating", genre: "US-UK Bất Hủ", lyrics: `I got you, moonlight, you're my starlight\nI need you all night, come on, dance with me...` },
{ title: "Save Your Tears", genre: "US-UK Bất Hủ", lyrics: `Save your tears for another day\nSave your tears for another day...` },
{ title: "Can't Feel My Face", genre: "US-UK Bất Hủ
  
];
